const mockEvents = {
 city: {
  id: 1007700,
  city: 'München',
  lat: 48.14,
  lon: 11.58,
  state: '',
  country: 'de',
  zip: 'meetup3',
  member_count: 1257
 },
 events: [
  {
   created: 1581676443000,
   duration: 5400000,
   id: '268705764',
   name: 'Running Kubernetes on Azure',
   rsvp_limit: 80,
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1583429400000,
   local_date: '2020-03-05',
   local_time: '18:30',
   updated: 1581927279000,
   utc_offset: 3600000,
   waitlist_count: 0,
   yes_rsvp_count: 71,
   venue: {
    id: 25766821,
    name: 'medialesson - Büro München',
    lat: 48.153099060058594,
    lon: 11.583580017089844,
    repinned: true,
    address_1: 'Leopoldstr. 8-10',
    address_2: 'c/o Nutrion Coworking Space',
    city: 'München',
    country: 'de',
    localized_country_name: 'Germany'
   },
   group: {
    created: 1520252901000,
    name: 'Software, Technology & Design Meetup München',
    id: 27731423,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'Software-Technology-Meetup-Munchen',
    who: 'Mitglieder',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/Software-Technology-Meetup-Munchen/events/268705764/',
   description: '<p>In this session Mohit Chhabra will give you insights how to run real apps on the most popular container orchestrator in Azure.</p> <p>We’ll review a high-level overview of the Azure Kubernetes Service (AKS) service and Azure Container Registry (ACR). We will start with the basic concepts of Kubernetes followed by understanding how AKS is different from the vanilla Kubernetes. Finally we\'ll be setting up and deploying a real world app on AKS. Feel free to follow along!</p> <p>Our speaker Mohit is working as Software Engineer at medialesson GmbH, Germany. He is currently Microsoft Most Valuable Professional for Microsoft Azure and former leader of BDotnet (India\'s Biggest offline community). He has delivered more than 50 sessions in the community and international conferences. Prior to this, Mohit was Microsoft Student Partner and Mozilla Student Representative. He was also India\'s first Azure Champion and the first person to intern in Microsoft Technology Center.</p> <p>This meetup will be hosted by medialesson, food and drinks will be provided. The session language is English. Please make sure you update your RSVP status 24h in advance so we don\'t waste any food!</p> ',
   how_to_find_us: 'The entry to building No. 8 is directly accessible from Leopoldstr. near Siegestor, walk down the broad spiral stairs down to the basement and enter trough the first glass door on the right hand.',
   visibility: 'public',
   member_pay_fee: false
  },
  {
   created: 1578507606000,
   duration: 10800000,
   id: '267752688',
   name: 'MeasureBowling #12 in Munich',
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1585245600000,
   local_date: '2020-03-26',
   local_time: '19:00',
   updated: 1578507752000,
   utc_offset: 3600000,
   waitlist_count: 0,
   yes_rsvp_count: 12,
   group: {
    created: 1543785470000,
    name: 'Analytics Pioneers Munich',
    id: 30635499,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'analytics-pioneers-munich',
    who: 'Mitglieder',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/analytics-pioneers-munich/events/267752688/',
   description: '<p>--- This is a prepayment event - Tickets: <a href=\'https://www.xing.com/events/measure-bowling-munich-2020-2355253\' class=\'linkified\'>https://www.xing.com/events/measure-bowling-munich-2020-2355253</a> ---</p> <p>We are proud to announce that measure bowling will come to munich!</p> <p>The goal of MeasureBowling is to build the Digital Analytics community, both locally and at the global level, with a fun social activity. There are no presentations or talks, just a relaxed evening of bowling.</p> <p>MeasureBowling is organized in 18 cities: Belfast, Berlin, Brussels, Cologne, Dallas, Gdansk, Istanbul, Lyon, Moscow, Munich, Nantes, New York City, Prague, San Francisco, Toronto, Utrecht, Vienna and Würzburg.</p> <p>MeasureBowling is held only once a year, so don’t miss this opportunity to meet the Digital Analytics community in Munich!</p> <p>The ticket for MeasureBowling Munich includes two hours of bowling and a welcome drink.</p> <p>Programm<br/>07:00 PM - Welcome<br/>07:30 PM - Getting ready<br/>08:00 PM - Bowling<br/>10:00 PM - Awarding ceremony + networking</p> ',
   visibility: 'public',
   member_pay_fee: false
  },
  {
   created: 1581937808000,
   duration: 10800000,
   id: '268771520',
   name: 'Save the date - Design Thinking Meetup',
   rsvp_limit: 4,
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1588091400000,
   local_date: '2020-04-28',
   local_time: '18:30',
   rsvp_open_offset: 'PT177H30M',
   updated: 1581943034000,
   utc_offset: 7200000,
   waitlist_count: 0,
   yes_rsvp_count: 4,
   group: {
    created: 1460553553000,
    name: 'Design Thinking München',
    id: 19836170,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'DT-Muc',
    who: 'Design Thinkers',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/DT-Muc/events/268771520/',
   description: '<p>Save the date for our next DT Meetup!</p> <p>If you are interested to host the next meetup, just drop us a message.</p> ',
   visibility: 'public',
   member_pay_fee: false
  },
  {
   created: 1582655856000,
   duration: 7200000,
   id: '268983616',
   name: 'Corporate Venturing neu gedacht mit Venture Client - für Startups & Corporates',
   rsvp_limit: 50,
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1583861400000,
   local_date: '2020-03-10',
   local_time: '18:30',
   updated: 1582707626000,
   utc_offset: 3600000,
   waitlist_count: 0,
   yes_rsvp_count: 27,
   venue: {
    id: 26806805,
    name: 'Resulting',
    lat: 48.135986328125,
    lon: 11.574705123901367,
    repinned: true,
    address_1: 'Rindermarkt 5',
    address_2: '5.Stock',
    city: 'München',
    country: 'de',
    localized_country_name: 'Germany'
   },
   group: {
    created: 1497098231000,
    name: 'München Business Model Design and Innovation Meetup',
    id: 24388597,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'Munchen-Business-Model-Design-Innovation-Meetup',
    who: 'Mitglieder',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/Munchen-Business-Model-Design-Innovation-Meetup/events/268983616/',
   description: '<p>Startups brauchen Kapital und Coaching. Aber vor allem brauchen sie schon möglichst früh zahlende Kunden. Das funktioniert mit dem Venture Client Modell. Als Venture Client kauft ein Corporate, anstelle von Eigenkapital, das Produkt eines Startups – auch wenn es sich noch in Prototypen-Phase befindet. Mit der Entwicklung der BMW Startup Garage haben die Gründer von 27pilots Corporate Venturing neu erfunden. Das Venture Client Modell nutzt gezielt die strategischen Stärken beider Partner und wurde inzwischen erfolgreich auch in weiteren Konzernen etabliert.</p> <p>Was bedeutet Venture Client für Startups und Corporates und wie unterscheidet sich das Format von Venture Capital?</p> <p>27pilots unterstützt Firmen bei der Einführung von Venture Client Einheiten und der erfolgreichen Skalierung von Startup Projekten. Dr. Maximilian Marquart, Co-Gründer von 27pilots, stellt uns das Venture Client Modell vor und erzählt von Erfolgsbeispielen.</p> ',
   how_to_find_us: 'Du findest uns im 5.Stock.',
   visibility: 'public',
   member_pay_fee: false
  },
  {
   created: 1582537287000,
   duration: 10800000,
   id: '268946861',
   name: 'Kanban Metriken + Open Space',
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1583861400000,
   local_date: '2020-03-10',
   local_time: '18:30',
   updated: 1582537287000,
   utc_offset: 3600000,
   waitlist_count: 0,
   yes_rsvp_count: 68,
   venue: {
    id: 25772139,
    name: 'it-agile GmbH München',
    lat: 48.1500244140625,
    lon: 11.546462059020996,
    repinned: true,
    address_1: 'Nyphenburgerstraße 86',
    address_2: '80636',
    city: 'München',
    country: 'de',
    localized_country_name: 'Germany'
   },
   group: {
    created: 1520863131000,
    name: 'Kanban Community München - Der alternative Weg zu Agile',
    id: 27806088,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'Kanban-Community-Munchen',
    who: 'Kanbunnys',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/Kanban-Community-Munchen/events/268946861/',
   description: '<p>Hallo liebe Kanbunnys,</p> <p>es ist wieder soweit: wir Kanbunnys treffen uns. Diesmal geht es neben dem Open Space, um die Metriken in Kanban. Wie können wir unser System messen, auswerten und neue Experimente ausprobieren.<br/>Neben den Metriken wird es auch eine Session zu Grundlagen Kanban geben und im Rahmen des Open Space habt ihr die Möglichkeit eure eigenen Themen und Fragen zu platzieren.</p> <p>Ist es für Dich das erste Mal bei der Kanban Community: komm einfach vorbei, höre zu, bring Dich ein, wo du willst, und hab Spaß :)</p> <p>Für Pizza und Bier (natürlich auch Softdrinks) ist ab 18:30 gesorgt.</p> <p>Viele Grüße<br/>Sebastian, Chris und Oliver</p> ',
   how_to_find_us: 'Die Büros von it-agile befinden sich im Hinterhof (an Stylight vorbei), Hauseingang ist bei einem Durchgang. Treppenhaus 3. 1. OG.',
   visibility: 'public',
   member_pay_fee: false
  },
  {
   created: 1582904629000,
   duration: 18000000,
   id: '269062468',
   name: 'Schloss  und Michael Ende (Momo) Museum - Castle Blutenburg',
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1583586000000,
   local_date: '2020-03-07',
   local_time: '14:00',
   updated: 1583162884000,
   utc_offset: 3600000,
   waitlist_count: 0,
   yes_rsvp_count: 15,
   venue: {
    id: 24314156,
    name: 'Hauptbahnhof Entrance ',
    lat: 48.14168167114258,
    lon: 11.559309959411621,
    repinned: true,
    address_1: 'Arnulfstraße 4',
    city: 'München ',
    country: 'DE',
    localized_country_name: 'Germany'
   },
   group: {
    created: 1493907703000,
    name: 'German Conversation Club Munich',
    id: 23587093,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'German-Conversation-Club-Munich',
    who: 'German Clubbers',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/German-Conversation-Club-Munich/events/269062468/',
   description: '<p>Wir laufen ab Bahnhof Pasing zum Schloß Blutenburg (ein ehemaliges Jagdschloss) und besichtigen dort den James-Krüss-Turm, die Binette-Schröder- Illustrationen im Kabinett und die Zeichnungen, Fotos und Buchausgaben von Michael Ende.</p> <p>Michael Ende ist mit Erich Kästner der berühmteste Kinderbuchautor Deutschlands. „Momo“ eines seiner berühmtesten Bücher existiert in über 50 Sprachen!</p> <p>Das im spät gotischen Stil erbaute Schloss Blutenburg wird gerne auch wegen der sehenswerten Schlosskapelle besucht. Nach dem Kulturgenuss fahren wir zur \'Pasinger Fabrik\' um etwas leckeres zu essen und zu trinken.<br/>Der Eintritt ins Schloss beträgt Euro 3.- und Organisationsgebühr für die Sprachschule Edeltraud Euro 3.-<br/>Ich freue mich auf diesen Ausflug der somit Kultur und Genuss verbindet.</p> <p>We walk from Pasing station to Schloss Blutenburg (a former hunting lodge) and visit the James-Krüss Tower, the Binette Schröder illustrations in the cabinet and the drawings, photos and book editions by Michael Ende.</p> <p>Michael Ende is with Erich Kästner the most famous children\'s book author in Germany. \'Momo\' one of his most famous books exists in over 50 languages!</p> <p>The castle Blutenburg which was built in late Gothic style, is also popular because of the castle chapel which is well worth seeing. After the cultural enjoyment we drive to the \'Pasinger Fabrik\' to eat and drink something delicious.<br/>The entrance fee to the castle is Euro 3 and the organization fee for the language school Edeltraud is Euro 3.<br/>I am looking forward to this excursion which combines culture and pleasure.</p> ',
   visibility: 'public',
   member_pay_fee: false
  },
  {
   created: 1581605836000,
   duration: 9000000,
   id: '268682611',
   name: 'TW presents: Lean backends using functional Kotlin',
   rsvp_limit: 150,
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1583429400000,
   local_date: '2020-03-05',
   local_time: '18:30',
   updated: 1582532931000,
   utc_offset: 3600000,
   waitlist_count: 14,
   yes_rsvp_count: 150,
   venue: {
    id: 25852478,
    name: 'ThoughtWorks Munich ',
    lat: 48.135501861572266,
    lon: 11.613557815551758,
    repinned: true,
    address_1: 'Bothestraße 11',
    city: 'München',
    country: 'de',
    localized_country_name: 'Germany'
   },
   group: {
    created: 1413448074000,
    name: 'ThoughtWorks Munich',
    id: 17658472,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'ThoughtWorks-Muenchen',
    who: 'Mitglieder',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/ThoughtWorks-Muenchen/events/268682611/',
   description: '<p>Join us for our first meetup in March with our colleagues Srishti and Mario!</p> <p>In this talk we are going to talk about building lean backends in Kotlin, using a functional approach.</p> <p>The language is well suited for this, as it is pragmatic, not afraid of borrowing ideas and has a burgeoning ecosystem. Many talks focus on Android development, but we want to go in the other direction and speak about server side code. Specifically, our focus will be on small services that interact with other services using REST APIs and JSON, in a microservices ecosystem.</p> <p>Kotlin is already quite functional, supporting things like immutability and null safety out of the box. Starting from there we will expand on these and other patterns, like avoiding exceptions and expressing logic as a sequence of transformations, with the help of the excellent Arrow library. We will show code that runs in our production applications that is both elegant and maintainable. You will be able to adopt some of our ideas incrementally and see the benefits for yourself.</p> <p>ABOUT SRISHTI:<br/>Srishti is a software developer and tech enthusiast. She is passionate about clean code, problem-solving, test-driven development, and constantly learning topics that help her to develop quality software.</p> <p>ABOUT MARIO:<br/>Mario develops software for a living. Then he goes home and continues reading about software because he just cannot get enough.<br/>At some point, somebody thought it was a good idea to make him the technical lead of an agile team. He quickly discovered that building things himself is not the same as helping somebody else figure it out.<br/>He learned, somewhat to his surprise, that he really enjoys sharing ideas. According to their feedback, other developers have managed to learn something from Mario. At least they don\'t tend to run away screaming, which is, as he thinks, a good thing.</p> <p>SNACKS:<br/>As always we are offering various snacks and, beer and soft drinks. No full meal, but something to nibble on.</p> <p>AGENDA:<br/>18:30 Doors open for snacks, drinks and mingle<br/>19:00 Talk and questions<br/>20:00 More questions, drinks and mingle</p> ',
   how_to_find_us: 'The entrance is right next to the entrance of the big bike shop “Stadler”. If you are standing in front of the entrance of Holiday Inn you have to go around the whole building to find our entrance.',
   visibility: 'public',
   member_pay_fee: false
  },
  {
   created: 1564129835000,
   duration: 7200000,
   id: 'qbmqfrybcfbkb',
   name: 'Shut Up & Write!™ Munich',
   rsvp_limit: 15,
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1583569800000,
   local_date: '2020-03-07',
   local_time: '09:30',
   rsvp_open_offset: 'PT163H30M',
   updated: 1564129835000,
   utc_offset: 3600000,
   waitlist_count: 5,
   yes_rsvp_count: 15,
   venue: {
    id: 25966475,
    name: 'Bellevue München',
    lat: 48.160736083984375,
    lon: 11.563915252685547,
    repinned: false,
    address_1: 'Schleißheimer Str. 142a',
    city: 'München',
    country: 'de',
    localized_country_name: 'Germany'
   },
   group: {
    created: 1532540208000,
    name: 'Shut Up & Write!® Munich',
    id: 29351354,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'shutupandwritemunich',
    who: 'Writers',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/shutupandwritemunich/events/qbmqfrybcfbkb/',
   description: '<p>Join us for an hour of writing! We’ve discovered that it’s strikingly helpful to write with other writers. See if it’s true for you at 09:30 on Saturday.</p> <p>Be it a book, blog, script, essay, dissertation, resume, melody, poem or just plain work stuff, you are invited to write it with us. No one will see what you\'ve written or give you unsolicited advice. Instead of just thinking about writing, come and get some real writing done.<br/>SCHEDULE:<br/>09:30 - SESSION 1: quick intros.<br/>09:45 - timer starts: write for 1 hour.<br/>10:45 - chat / take off / keep writing for another timed hour (starting at ~11:15).</p> <p>OPTIONAL SOCIALIZING happens after we\'re done with the first/second writing hour. Writing is very solitary. Connecting (and sometimes even commiserating) with other writers is a cool thing.<br/>BEING LATE IS OKAY: just show up and get settled, then check-in with me after the session. (I’ll be the person with the Shut Up &amp; Write! sign.) If you were on time, please be willing to make room for the friendly latecomer.<br/>Happy writing and I look forward to seeing you!</p> <p>What Should I Bring?<br/>Whatever you need to be able to write!<br/>Bring earbuds/earplugs if you want to block the cafe’s overhead music or the occasional conversation by other patrons.<br/>There should be enough sockets to charge your devices, but make sure to charge them just in case! :)</p> <p>Other Important Details:<br/>GUIDELINES: Please thank our hosts by purchasing something.<br/>FUTURE LOCATIONS: If you have ideas about where and when we should meet, please share them! :)<br/>If you\'re on the waiting list, but still really really want to come, feel free to drop by — but in case we end up being too large of a group to manage, or we don\'t find enough free seats, the priority is on the folks with the \'going\' RSVPs!</p> ',
   how_to_find_us: 'Look for the Shut up & Write! sign or ask for Arnaud ',
   visibility: 'public',
   pro_is_email_shared: false,
   member_pay_fee: false
  },
  {
   created: 1580738783000,
   duration: 7200000,
   fee: {
    accepts: 'paypal',
    amount: 10,
    currency: 'EUR',
    description: '',
    label: 'Price',
    required: true
   },
   id: '268422505',
   name: 'Workshop: Social Media for Authors',
   rsvp_limit: 15,
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1584183600000,
   local_date: '2020-03-14',
   local_time: '12:00',
   updated: 1580738783000,
   utc_offset: 3600000,
   waitlist_count: 0,
   yes_rsvp_count: 1,
   group: {
    created: 1540275214000,
    name: 'Happy Writing: Munich',
    id: 30375868,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'Happy-Writing-Munich',
    who: 'Members',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/Happy-Writing-Munich/events/268422505/',
   description: '<p>If you\'re in the modern publishing landscape, you might see social media as a barrier. Some agents require a specific following number to even look at your work. While it\'s not for everyone, and certainly not everyone needs to be strong on social media, if this is an area you want to know more about, we\'re here to teach you!</p> <p>This workshop will be led by Dionne. In addition to teaching Social Media Marketing at EU Business School, Dionne is a certified Goal Achievement Life Coach. She actively coaches authors in building their platform and fine tuning their socials, and has helped build some of the largest Twitter tags and very successful author YouTube accounts with her clients.</p> <p>Location will be announced closer to the workshop depending on how many people sign up.</p> ',
   visibility: 'public',
   member_pay_fee: false
  },
  {
   created: 1576311322000,
   duration: 7200000,
   id: '267182421',
   name: 'Andrew Pruski - Chaos Engineering for SQL Server',
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1587661200000,
   local_date: '2020-04-23',
   local_time: '19:00',
   updated: 1578403978000,
   utc_offset: 7200000,
   waitlist_count: 0,
   yes_rsvp_count: 11,
   group: {
    created: 1462514436000,
    name: 'Microsoft Data Platform Community - PASS Deutschland e.V.',
    id: 19921609,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'pass-bayern',
    who: 'Data Monsters',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/pass-bayern/events/267182421/',
   description: '<p>In this session we will explore the concept of Chaos Engineering, its core concepts, and how it has been implemented at various companies.</p> <p>Then we\'ll look at how it can be implemented with regard to SQL Server. SQL has various different high availability solutions but can you be sure that they\'ll react as expected to a real world issue? Has your HA architecture only ever been tested in a planned maintenance window?</p> <p>We\'ll also have some fun by looking at KubeInvaders, a chaos engineering tool for Kubernetes...using Space Invaders!</p> <p>This session is for SQL Server DBAs and Developers who want to know how Chaos Engineering works and want to learn its main principles.</p> <p>Andrew Pruski</p> <p>SQL Server DBA originally from Wales but now exploring Ireland</p> <p>I\'m a SQL Server DBA and Microsoft Data Platform MVP, you can find me on twitter @dbafromthecold and blogging at dbafromthecold.com</p> ',
   visibility: 'public',
   member_pay_fee: false
  },
  {
   created: 1582538359000,
   duration: 10800000,
   id: '268947102',
   name: '\'get Kanban\' Spiel + Open Space',
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1589905800000,
   local_date: '2020-05-19',
   local_time: '18:30',
   updated: 1582538723000,
   utc_offset: 7200000,
   waitlist_count: 0,
   yes_rsvp_count: 7,
   venue: {
    id: 25772139,
    name: 'it-agile GmbH München',
    lat: 48.1500244140625,
    lon: 11.546462059020996,
    repinned: true,
    address_1: 'Nyphenburgerstraße 86',
    address_2: '80636',
    city: 'München',
    country: 'de',
    localized_country_name: 'Germany'
   },
   group: {
    created: 1520863131000,
    name: 'Kanban Community München - Der alternative Weg zu Agile',
    id: 27806088,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'Kanban-Community-Munchen',
    who: 'Kanbunnys',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/Kanban-Community-Munchen/events/268947102/',
   description: '<p>Hallo liebe Kanbunnys,</p> <p>es ist wieder soweit: wir Kanbunnys treffen uns. Wir machen wieder einen Open Space und für Leute die Lust haben, gibt es die Möglichkeit getKanban zu spielen. Es ist eine Simulation die Limitierung von Arbeit, Priorisieren, gemeinsam Entscheiden, tracken von Metriken spielerisch vermittelt. Wir entscheiden zu Beginn des Open Space wer getKanban spielen will. Die Voraussetzung ist, dass sich mindestens 4 Leute finden die die ganze Zeit dabei sind.</p> <p>Neben getKanban habt ihr im Rahmen des Open Space die Möglichkeit eure eigenen Themen und Fragen zu platzieren.</p> <p>Ist es für Dich das erste Mal bei der Kanban Community: komm einfach vorbei, höre zu, bring Dich ein, wo du willst, und hab Spaß :)</p> <p>Für Pizza und Bier (natürlich auch Softdrinks) ist ab 18:30 gesorgt.</p> <p>Viele Grüße<br/>Sebastian, Chris und Oliver</p> ',
   how_to_find_us: 'Die Büros von it-agile befinden sich im Hinterhof (an Stylight vorbei), Hauseingang ist bei einem Durchgang. Treppenhaus 3. 1. OG.',
   visibility: 'public',
   member_pay_fee: false
  },
  {
   created: 1582544892000,
   duration: 25200000,
   id: '268948509',
   name: 'Salsa Party am Stachus',
   rsvp_limit: 50,
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1583607600000,
   local_date: '2020-03-07',
   local_time: '20:00',
   updated: 1582548335000,
   utc_offset: 3600000,
   waitlist_count: 0,
   yes_rsvp_count: 22,
   venue: {
    id: 26875833,
    name: 'Tanzschule Am Stachus',
    lat: 48.138160705566406,
    lon: 11.565716743469238,
    repinned: false,
    address_1: 'sonnenstraße 7',
    city: 'München',
    country: 'de',
    localized_country_name: 'Germany'
   },
   group: {
    created: 1522224947000,
    name: 'Munich Salsa, Bachata & Kizomba Friends Meetup',
    id: 27972418,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'Munich-Salsa-Bachata-Kizomba-Friends-Meetup',
    who: 'Loquitos',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/Munich-Salsa-Bachata-Kizomba-Friends-Meetup/events/268948509/',
   description: '<p>Salsa Party am Stachus with Salsamás &amp; Friends<br/>Salsa Classics, Salsa Cubana, Salsa Romantica, Bachata &amp; Kizomba</p> <p>Every first Saturday !<br/>=&gt; 20:00-03:00h</p> <p>* Free entry for all!<br/>* 20:00-21:00 - dance classes for free</p> <p>The „Tanzschule am Stachus“ invites all salsa friends to the monthly „Salsa Party am Stachus with Salsamás &amp; Friends“. At the beginning of the evening the dance school Salsamás Munich will offer dance classes for free. DJ Nicemixx &amp; Friends will take care of the good music mix! This event is organized with the friendly support of the dance school Salsamás Munich.</p> <p>Of course, the „Tanzschule am Stachus“ team will offer refreshing drinks and delicious cocktails at the bar.</p> <p>We look forward to your coming :-)</p> <p>====================================</p> <p>Timetable:<br/>20: 00-20: 30 - Salsa intermediate class „lifts and dips“ with Salsamás-Team<br/>20: 30-21: 00 - Salsa,Bachata &amp; Kizomba beginner class with Salsamás-Team<br/>22: 00-03: 00 - Best of Salsa Classics, Salsa Cubana, Salsa Romantica, Bachata &amp; Kizomba</p> <p>Tanzschule am Stachus<br/>Sonnenstraße 7 . 80331 München</p> <p>Your „Tanzschule am Stachus“ &amp; Salsamás teams</p> <p>Further information:<br/>Mobile: [masked]<br/>E-Mail: [masked]</p> <p>Deutsch:</p> <p>Salsa Party am Stachus with Salsamás &amp; Friends<br/>Salsa Classics, Salsa Cubana, Salsa Romantica, Bachata &amp; Kizomba</p> <p>====================================<br/>Immer am ersten Samstag des Monats!<br/>====================================</p> <p>Die „Tanzschule am Stachus“ ladet alle Salsa Freunde, zu der monatlichen „Salsa Party am Stachus mit Salsamás &amp; Friends“ ein. Zu Beginn des Abends wird die Tanzschule Salsamás Munich kostenlose Tanzkurse anbieten. DJ Nicemixx &amp; Friends werden für den guten Musikmix sorgen! Dieses Event wird mit der freundlichen Unterstützung der Tanzschule Salsamás Munich organisiert.</p> <p>Selbstverständlich wird die „Tanzschule am Stachus“ alle Gäste mit erfrischenden Getränken und leckeren Cocktails an der Bar verwöhnen.</p> <p>Wir freuen uns auf euer Kommen :-)</p> <p>Salsa Party am Stachus with Salsamás &amp; Friends Salsa Classics, Salsa Cubana, Salsa Romantica, Bachata &amp; Kizomba</p> <p>====================================<br/>Immer am ersten Samstag des Monats!<br/>====================================</p> <p>Programm:<br/>20: 00-20: 30 - Salsa intermediate class „lifts and dips“ with Salsamás-Team<br/>20: 30-21: 00 - Salsa,Bachata &amp; Kizomba beginner class with Salsamás-Team<br/>22: 00-03: 00 - Best of Salsa Classics, Salsa Cubana, Salsa Romantica, Bachata &amp; Kizomba</p> <p>Tanzschule am Stachus<br/>Sonnenstraße 7 . 80331 München</p> <p>Euer „TANZSCHULE AM STACHUS“ &amp; Salsamás Teams</p> <p>Weitere Infos unter: [masked]</p> ',
   visibility: 'public',
   member_pay_fee: false
  },
  {
   created: 1576311358000,
   duration: 7200000,
   id: '267182423',
   name: 'Andre Kamman & William Durkin - Topic to be announced',
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1589475600000,
   local_date: '2020-05-14',
   local_time: '19:00',
   updated: 1576577241000,
   utc_offset: 7200000,
   waitlist_count: 0,
   yes_rsvp_count: 6,
   group: {
    created: 1462514436000,
    name: 'Microsoft Data Platform Community - PASS Deutschland e.V.',
    id: 19921609,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'pass-bayern',
    who: 'Data Monsters',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/pass-bayern/events/267182423/',
   description: '<p>Speaker and topic to be announced</p> ',
   visibility: 'public',
   member_pay_fee: false
  },
  {
   created: 1581941816000,
   duration: 10800000,
   id: 'pjfhprybcfbfb',
   name: 'Shut Up & Write!™ Munich',
   rsvp_limit: 12,
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1583254800000,
   local_date: '2020-03-03',
   local_time: '18:00',
   rsvp_open_offset: 'PT168H',
   updated: 1581941816000,
   utc_offset: 3600000,
   waitlist_count: 10,
   yes_rsvp_count: 12,
   venue: {
    id: 25711269,
    name: 'Cotidiano Promenadeplatz',
    lat: 48.14008331298828,
    lon: 11.569615364074707,
    repinned: true,
    address_1: 'Maxburgstraße 4',
    city: 'München',
    country: 'de',
    localized_country_name: 'Germany'
   },
   group: {
    created: 1532540208000,
    name: 'Shut Up & Write!® Munich',
    id: 29351354,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'shutupandwritemunich',
    who: 'Writers',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/shutupandwritemunich/events/pjfhprybcfbfb/',
   description: '<p>Join us for an hour of writing! We’ve discovered that it’s strikingly helpful to write with other writers.</p> <p>Be it a book, blog, script, essay, dissertation, resume, melody, poem or just plain work stuff, you are invited to write it with us. No one will see what you\'ve written or give you unsolicited advice. Instead of just thinking about writing, come and get some real writing done.<br/>SCHEDULE (roughly):</p> <p>18:15 - SESSION 1: quick intros.<br/>18:20 - timer starts: write for 1 hour.<br/>19:20 - chat / take off / keep writing for another timed hour (starting at ~19:45).</p> <p>OPTIONAL SOCIALIZING happens after we\'re done with the first/second writing hour. Writing is very solitary. Connecting (and sometimes even commiserating) with other writers is a cool thing.<br/>BEING LATE IS OKAY: just show up and get settled, then check-in with me after the session. (I’ll be the person with the Shut Up &amp; Write! sign.) If you were on time, please be willing to make room for the friendly latecomer.<br/>Happy writing and I look forward to seeing you!</p> <p>What Should I Bring?<br/>Whatever you need to be able to write!<br/>Bring earbuds/earplugs if you want to block the cafe’s overhead music or the occasional conversation by other patrons.<br/>There should be enough sockets to charge your devices, but make sure to charge them just in case! :)</p> <p>Other Important Details:<br/>GUIDELINES: Please thank our hosts by purchasing something.<br/>FUTURE LOCATIONS: If you have ideas about where and when we should meet, please share them! :)<br/>If you\'re on the waiting list, but still really really want to come, feel free to drop by — but in case we end up being too large of a group to manage, or we don\'t find enough free seats, the priority is on the folks with the \'going\' RSVPs!</p> ',
   how_to_find_us: 'Reservations under Spiegel',
   visibility: 'public',
   pro_is_email_shared: false,
   member_pay_fee: false
  },
  {
   created: 1581590402000,
   duration: 12600000,
   id: '268679192',
   name: 'Search Meetup Munich - March Edition',
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1583429400000,
   local_date: '2020-03-05',
   local_time: '18:30',
   updated: 1582211405000,
   utc_offset: 3600000,
   waitlist_count: 0,
   yes_rsvp_count: 60,
   venue: {
    id: 26870732,
    name: 'Data Reply (Room Reply Solar, near the main.entrance)',
    lat: 48.14474868774414,
    lon: 11.538175582885742,
    repinned: false,
    address_1: 'Luise-Ullrich- Str. 14',
    city: 'München',
    country: 'DE',
    localized_country_name: 'Germany'
   },
   group: {
    created: 1384777702000,
    name: 'Search Meetup Munich',
    id: 11150702,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'Search-Meetup-Munich',
    who: 'Searchers Munchen',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/Search-Meetup-Munich/events/268679192/',
   description: '<p>THIS IS A FREE EVENT - PLEASE FINISH YOUR RSVP IN THE LINK BELOW</p> <p>&lt;br/&gt;<a href=\'https://community.elastic.co/events/details/elastic-munich-presents-search-meetup-munich-march-edition/\' class=\'linkified\'>https://community.elastic.co/events/details/elastic-munich-presents-search-meetup-munich-march-edition/</a></p> <p>&amp;lt;p&amp;gt;The Munich Search Meetup is all about search technologies. This is the 34th meetup, second one in 2020!&amp;amp;nbsp;Data Reply has stepped up quickly after another hoster had to cancel, so thanks so much to them!&amp;lt;br&amp;gt;&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;Agenda:&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;18:30 - 19:00 Gathering, grab snacks &amp;amp;amp; drinks&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;19:00 - 19:30 Running the Elastic Stack on GCP by Markus Klose&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;19:30 - 20:15 Database Internals&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;20:15 - 20:30 Break&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;20:30 - 21:00 Tips and Tricks from Elastic Support: Setting up and running your cluster by Cris da Rocha&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;21:00 -&amp;amp;nbsp; Mingling and hanging out&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;&amp;lt;br&amp;gt;&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;Talks overview:&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;&amp;lt;br&amp;gt;&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;Tips and Tricks from Elastic Support: Setting up and running your cluster&amp;lt;/p&amp;gt;&amp;lt;p&amp;gt;Setting up and running an Elasticsearch cluster is easy at first. Proper planning and design can help preventing many issues when going live gets real. We&amp;#39;ll present some tips and tricks, learned from the experience of Elastic Support on how to do things better.&amp;lt;br&amp;gt;&amp;lt;/p&amp;gt;&lt;/p&gt;</p> <p>Agenda&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>&lt;br/&gt;---&lt;br/&gt;</p> <p>&lt;br/&gt;---&lt;br/&gt;</p> <p>&lt;br/&gt;</p> <p>THIS IS A FREE EVENT - PLEASE FINISH YOUR RSVP IN THE LINK BELOW</p> <p>&lt;br/&gt;<a href=\'https://community.elastic.co/events/details/elastic-munich-presents-search-meetup-munich-march-edition/\' class=\'linkified\'>https://community.elastic.co/events/details/elastic-munich-presents-search-meetup-munich-march-edition/</a></p> ',
   visibility: 'public',
   pro_is_email_shared: false,
   member_pay_fee: false
  },
  {
   created: 1581593602000,
   duration: 7200000,
   id: '268679736',
   name: 'How To Design Awesome CSS Components with Le Wagon',
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1584034200000,
   local_date: '2020-03-12',
   local_time: '18:30',
   updated: 1581593602000,
   utc_offset: 3600000,
   waitlist_count: 0,
   yes_rsvp_count: 6,
   group: {
    created: 1574935324000,
    name: 'Le Wagon Munich - Coding Bootcamp',
    id: 33056128,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'Le-Wagon-Munich',
    who: 'Mitglieder',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/Le-Wagon-Munich/events/268679736/',
   description: '<p>⭐️PLEASE REGISTER VIA EVENTBRITE : <a href=\'https://lew.ag/mucssmarch\' class=\'linkified\'>https://lew.ag/mucssmarch</a> ⭐️</p> <p>DISCLAIMER: you should have some basic HTML/CSS knowledge to come.</p> <p>This is a FREE workshop on CSS Components Design!</p> <p>If you already have some knowledge of HTML, CSS and have briefly played with Bootstrap (<a href=\'http://getbootstrap.com/\' class=\'linkified\'>http://getbootstrap.com/</a>), then this workshop will be great fun.</p> <p>If you\'ve been to one of our \'Build your landing page in 2 hours\' / \'Introduction to HTML &amp; CSS\' workshops, this will be the perfect follow-up.</p> <p>👇In this workshop you will be learning to code 👇</p> <p>- Navbars</p> <p>- Buttons</p> <p>- Cards</p> <p>- Dropdown-lists</p> <p>- Banners &amp; badges</p> <p>- Other UI components that you can find on most apps</p> <p>To do that, we will cover lots of cool CSS techniques and patterns by reproducing components from existing websites (Product Hunt or Medium). Positioning techniques, flexbox, transitions, filters, etc.. you\'ll learn a lot of crazy CSS stuff, we promise!</p> <p>👇How to prepare and what to bring👇</p> <p>1) Your own laptop - FULLY CHARGED</p> <p>2) Make sure you have Google Chrome installed and running on your computer: <a href=\'https://www.google.com/chrome/\' class=\'linkified\'>https://www.google.com/chrome/</a></p> <p>3) Download SublimeText Editor: <a href=\'http://www.sublimetext.com/3\' class=\'linkified\'>http://www.sublimetext.com/3</a> (<a href=\'http://www.sublimetext.com/2\' class=\'linkified\'>http://www.sublimetext.com/2</a>)</p> <p>⭐️PLEASE REGISTER VIA EVENTBRITE : <a href=\'https://lew.ag/mucssmarch\' class=\'linkified\'>https://lew.ag/mucssmarch</a> ⭐️</p> <p>***************************************</p> <p>Plug and Play is the ultimate innovation platform, co-working community and event space established in late 2017 in Munich, with 3 different industry focus areas: Insurtech, Health and Retailtech. Together with our partners in Germany and around the globe, we are building a startup, corporate and venture capital ecosystem in the heart of Bavaria!</p> <p>👉Website: <a href=\'https://www.plugandplaytechcenter.com/munich/\' class=\'linkified\'>https://www.plugandplaytechcenter.com/munich/</a></p> <p>👉LinkedIn : <a href=\'https://www.linkedin.com/company/plug-and-play-munich\' class=\'linkified\'>https://www.linkedin.com/company/plug-and-play-munich</a></p> <p>👉Facebook : <a href=\'https://www.facebook.com/pnpMunich/\' class=\'linkified\'>https://www.facebook.com/pnpMunich/</a></p> <p>👉 Contact : [masked]</p> <p>***************************************<br/>Le Wagon is Europe\'s leading coding school for entrepreneurs and creative people. We are now present in 35 cities worldwide, with over 120 startups in operation, and have been rated the no#1 coding bootcamp worldwide on Course Report &amp; Switchup! Our full-stack web development course equips aspiring entrepreneurs, product managers, designers, and junior developers with the technical skills they need to build great products and startups!</p> <p>The next batch in Munich starts on March 30th 2020. Further details about the course and how to apply can be found here (<a href=\'https://www.lewagon.com/munich\' class=\'linkified\'>https://www.lewagon.com/munich</a>).</p> <p>👉Join our Meetup group: <a href=\'https://www.meetup.com/de-DE/Le-Wagon-Munich/\' class=\'linkified\'>https://www.meetup.com/de-DE/Le-Wagon-Munich/</a></p> <p>👉Like us on Facebook: <a href=\'http://facebook.com/lewagongermany\' class=\'linkified\'>http://facebook.com/lewagongermany</a></p> <p>👉Follow us on Twitter: <a href=\'https://twitter.com/lewagonmunich\' class=\'linkified\'>https://twitter.com/lewagonmunich</a></p> <p>👉Look at some lovely photos on Instagram: <a href=\'https://www.instagram.com/lewagonmunich/\' class=\'linkified\'>https://www.instagram.com/lewagonmunich/</a></p> <p>***************************************</p> <p>We look forward to meeting you soon!</p> <p>Team Le Wagon</p> ',
   visibility: 'public',
   member_pay_fee: false
  },
  {
   created: 1581937631000,
   duration: 10800000,
   id: '268771486',
   name: 'Save the date - Design Thinking Meetup',
   rsvp_limit: 4,
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1584466200000,
   local_date: '2020-03-17',
   local_time: '18:30',
   rsvp_open_offset: 'PT177H30M',
   updated: 1581943001000,
   utc_offset: 3600000,
   waitlist_count: 0,
   yes_rsvp_count: 4,
   group: {
    created: 1460553553000,
    name: 'Design Thinking München',
    id: 19836170,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'DT-Muc',
    who: 'Design Thinkers',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/DT-Muc/events/268771486/',
   description: '<p>Save the date for our next DT Meetup!</p> <p>If you are interested to host the next meetup, just drop us a message.</p> ',
   visibility: 'public',
   member_pay_fee: false
  },
  {
   created: 1581941816000,
   duration: 10800000,
   id: 'pjfhprybcfbnb',
   name: 'Shut Up & Write!™ Munich',
   rsvp_limit: 12,
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1583859600000,
   local_date: '2020-03-10',
   local_time: '18:00',
   rsvp_open_offset: 'PT168H',
   updated: 1581941816000,
   utc_offset: 3600000,
   waitlist_count: 0,
   yes_rsvp_count: 1,
   venue: {
    id: 25711269,
    name: 'Cotidiano Promenadeplatz',
    lat: 48.14008331298828,
    lon: 11.569615364074707,
    repinned: true,
    address_1: 'Maxburgstraße 4',
    city: 'München',
    country: 'de',
    localized_country_name: 'Germany'
   },
   group: {
    created: 1532540208000,
    name: 'Shut Up & Write!® Munich',
    id: 29351354,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'shutupandwritemunich',
    who: 'Writers',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/shutupandwritemunich/events/pjfhprybcfbnb/',
   description: '<p>Join us for an hour of writing! We’ve discovered that it’s strikingly helpful to write with other writers.</p> <p>Be it a book, blog, script, essay, dissertation, resume, melody, poem or just plain work stuff, you are invited to write it with us. No one will see what you\'ve written or give you unsolicited advice. Instead of just thinking about writing, come and get some real writing done.<br/>SCHEDULE (roughly):</p> <p>18:15 - SESSION 1: quick intros.<br/>18:20 - timer starts: write for 1 hour.<br/>19:20 - chat / take off / keep writing for another timed hour (starting at ~19:45).</p> <p>OPTIONAL SOCIALIZING happens after we\'re done with the first/second writing hour. Writing is very solitary. Connecting (and sometimes even commiserating) with other writers is a cool thing.<br/>BEING LATE IS OKAY: just show up and get settled, then check-in with me after the session. (I’ll be the person with the Shut Up &amp; Write! sign.) If you were on time, please be willing to make room for the friendly latecomer.<br/>Happy writing and I look forward to seeing you!</p> <p>What Should I Bring?<br/>Whatever you need to be able to write!<br/>Bring earbuds/earplugs if you want to block the cafe’s overhead music or the occasional conversation by other patrons.<br/>There should be enough sockets to charge your devices, but make sure to charge them just in case! :)</p> <p>Other Important Details:<br/>GUIDELINES: Please thank our hosts by purchasing something.<br/>FUTURE LOCATIONS: If you have ideas about where and when we should meet, please share them! :)<br/>If you\'re on the waiting list, but still really really want to come, feel free to drop by — but in case we end up being too large of a group to manage, or we don\'t find enough free seats, the priority is on the folks with the \'going\' RSVPs!</p> ',
   how_to_find_us: 'Reservations under Spiegel',
   visibility: 'public',
   pro_is_email_shared: false,
   member_pay_fee: false
  },
  {
   created: 1536494061000,
   duration: 16200000,
   id: 'snxjfqybcfbmb',
   name: 'Meeple Monday',
   rsvp_limit: 20,
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1583775000000,
   local_date: '2020-03-09',
   local_time: '18:30',
   rsvp_open_offset: 'PT186H30M',
   rsvp_close_offset: 'PT30M',
   updated: 1536494061000,
   utc_offset: 3600000,
   waitlist_count: 0,
   yes_rsvp_count: 1,
   venue: {
    id: 25689781,
    name: 'Kulturladen Westend',
    lat: 48.134117126464844,
    lon: 11.541715621948242,
    repinned: true,
    address_1: 'Ligsalzstrasse 44',
    city: 'München ',
    country: 'de',
    localized_country_name: 'Germany'
   },
   group: {
    created: 1449524089000,
    name: 'Munich Boardgame Meetup',
    id: 19191650,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'Munich-Boardgame-Meetup',
    who: 'Boardgamers',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/Munich-Boardgame-Meetup/events/snxjfqybcfbmb/',
   description: '<p>Every second Monday of the month. Location right next to U-Bahn Schwanthalerhöhe. As always: games are usually English or language neutral. There is a fridge with drinks for 1,50 each. Please bring your favorite Games or just join. RSVP opens one week before the event.</p> ',
   visibility: 'public',
   member_pay_fee: false
  },
  {
   created: 1582389241000,
   duration: 3600000,
   id: '268908409',
   name: 'Webinar: Innovative Lösungen mit dem Design Sprint',
   date_in_series_pattern: false,
   status: 'upcoming',
   time: 1583254800000,
   local_date: '2020-03-03',
   local_time: '18:00',
   updated: 1582389334000,
   utc_offset: 3600000,
   waitlist_count: 0,
   yes_rsvp_count: 49,
   venue: {
    id: 26809364,
    name: 'Online',
    lat: 48.13512420654297,
    lon: 11.58198070526123,
    repinned: false,
    address_1: 'Resulting',
    city: 'München',
    country: 'de',
    localized_country_name: 'Germany'
   },
   group: {
    created: 1497098231000,
    name: 'München Business Model Design and Innovation Meetup',
    id: 24388597,
    join_mode: 'open',
    lat: 48.13999938964844,
    lon: 11.579999923706055,
    urlname: 'Munchen-Business-Model-Design-Innovation-Meetup',
    who: 'Mitglieder',
    localized_location: 'München, Germany',
    state: '',
    country: 'de',
    region: 'en_US',
    timezone: 'Europe/Berlin'
   },
   link: 'https://www.meetup.com/Munchen-Business-Model-Design-Innovation-Meetup/events/268908409/',
   description: '<p>Endlose Diskussionen und langwierige Probierschleifen? Das Gestalten von innovativen Lösungsansätzen ist eine komplexe Herausforderung.</p> <p>Wie können Teams Ideen schnell und effizient im Einklang mit den strategischen Zielen weiterentwickeln und testen?</p> <p>Google Entwickler Jake Knapp hat dazu die Methode “Design Sprint” konzeptioniert und in vielen Fällen erfolgreich angewendet.<br/>In nur 4 Tagen designen Teams ein Lösungskonzept und testen die Umsetzung. So können Entwicklungszeiten extrem verkürzt und Risiken reduziert werden.</p> <p>Im Webinar lernst Du die wichtigsten Grundlagen zum Design Sprint:</p> <p>Was ist das Besondere am Design Sprint?<br/>Wie läuft ein Design Sprint?<br/>Wann ist das Format Design Sprint ideal?</p> <p>Achtung, dies ist eine Online-Veranstaltung!</p> <p>Bitte registriere Dich hier, dann erhältst Du den Zugangslink zum virtuellen Webinar-Raum:</p> <p><a href=\'https://info-9382.gr8.com\' class=\'linkified\'>https://info-9382.gr8.com</a></p> ',
   how_to_find_us: 'Du erhältst einen Zugangslink zum virtuellen Webinar-Raum.',
   visibility: 'public',
   member_pay_fee: false
  }
 ]
};

export { mockEvents };